=== szkrisi99/IDA58U_XMLGyak/IDA58U_1011/IDA58U_kurzusfelvetel.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:simpleType name="tanevType">
        <xs:restriction base="xs:string">
            <xs:pattern value="\d{4}\/d{4}{\s}?I(I)?." />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="egyetemType">
        <xs:restriction base="xs:string">
            <xs:pattern value="ME" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="idType">
        <xs:restriction base="xs:string">
            <xs:minLength value="5" />
            <xs:maxLength value="10" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="igenNemType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="igen" />
            <xs:enumeration value="nem" />
        </xs:restriction>
    </xs:simpleType>

    <xs:element name="kurzusfelvetel">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="hallgato"/>
                <xs:element ref="kurzusok"/>
            </xs:sequence>
            <xs:attribute name="tanev" type="tanevType" use="required" />
            <xs:attribute name="egyetem" type="egyetemType" use="required" />
        </xs:complexType>
    </xs:element>

    <xs:element name="hallgato">
        <xs:complexType>
            <xs:all>
                <xs:element name="hnev" type="xs:string"/>
                <xs:element name="szulev" type="xs:string"/>
                <xs:element name="szak">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attribute name="evf" type="xs:integer" use="required"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
            </xs:all>
            <xs:attribute name="id" type="idType" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="kurzusok">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="kurzus" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:all>
                            <xs:element name="kurzusnev" type="xs:string"/>
                            <xs:element name="kredit">
                                <xs:simpleType>
                                    <xs:restriction base="xs:integer">
                                        <xs:minInclusive value="0"/>
                                        <xs:maxInclusive value="30"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="hely" type="xs:string"/>
                            <xs:element name="idopont" type="xs:string" minOccurs="0"/>
                            <xs:element name="oktato" type="xs:string" minOccurs="0"/>
                            <xs:element name="oraado" type="xs:string" minOccurs="0"/>
                        </xs:all>
                        <xs:attribute name="id" type="idType" use="required"/>
                        <xs:attribute name="jovahagyas" type="igenNemType" use="optional" default="nem"/>
                        <xs:attribute name="nyelv" type="xs:string" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== szkrisi99/IDA58U_XMLGyak/IDA58U_1011/IDA58U_kurzusfelvetel.xml
<?xml version="1.0" encoding="UTF-8"?>
<kurzusfelvetel tanev="2023/2024 I." egyetem="ME" xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="IDA58U_kurzusfelvetel.xsd">
    
    <hallgato id="KPRLNM.ME">
        <hnev></hnev>
        <szulev></szulev>
        <szak evf="5"></szak>
    </hallgato>

    <kurzusok>
        <kurzus id="GEIAL322-B" nyelv="magyar">
            <kurzusnev>Adatkezelés XML környezetben</kurzusnev>
            <kredit>5</kredit>
            <hely>XXXII.</hely>
            <idopont>Kedd 12:00-14:00</idopont>
            <oktato>Dr. Bednarik László</oktato>
        </kurzus>
        <kurzus id="GEIAL304-B" nyelv="magyar" jovahagyas="igen">
            <kurzusnev>Számítógép hálózatok</kurzusnev>
            <kredit>5</kredit>
            <hely>II A2 mfsz.</hely>
            <idopont>Szerda 08:00-10:00</idopont>
            <oktato>Dr. Kovács Szilveszter</oktato>
            <oraado>Óraadó Tanár</oraado>
        </kurzus>
        <kurzus id="GEMAK231-B" nyelv="magyar" jovahagyas="nem">
            <kurzusnev>Lineáris algebra numerikus módszerei</kurzusnev>
            <kredit>4</kredit>
            <hely>X ea.</hely>
            <idopont>Hétfő 08:00-10:00</idopont>
            <oktato>Dr. Karácsony Zsolt</oktato>
        </kurzus>
    </kurzusok>

</kurzusfelvetel>
